name: 'HCP Terraform Run'
description: 'Trigger an HCP Terraform run using official HashiCorp GitHub Actions'

inputs:
  tfc_organization:
    description: 'HCP Terraform organization name'
    required: true
  tfc_workspace:
    description: 'HCP Terraform workspace name'
    required: true
  terraform_directory:
    description: 'Path to Terraform configuration'
    required: false
    default: '.'
  tfc_token:
    description: 'HCP Terraform API token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Upload Terraform Configuration
      uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.3.2
      with:
        workspace: ${{ inputs.tfc_workspace }}
        organization: ${{ inputs.tfc_organization }}
        path: ${{ inputs.terraform_directory }}
        token: ${{ inputs.tfc_token }}

    - name: Create Terraform Run
      id: create-run
      uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.2
      with:
        workspace: ${{ inputs.tfc_workspace }}
        organization: ${{ inputs.tfc_organization }}
        message: 'Triggered via GitHub Actions'
        token: ${{ inputs.tfc_token }}

    - name: Wait for Plan & Display
      uses: hashicorp/tfc-workflows-github/actions/plan-output@v1.3.2
      with:
        plan: ${{ steps.create-run.outputs.plan_id }}
        token: ${{ inputs.tfc_token }}

    - name: Auto Apply (if not speculative or destroy)
      # Ensure run is not from PR or pre-merge context and not a destroy operation.
      if: steps.create-run.outputs.is_speculative == 'false' && steps.create-run.outputs.is_destroy == 'false'
      uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.2
      with:
        run: ${{ steps.create-run.outputs.run_id }}
        token: ${{ inputs.tfc_token }}
